name: Build commit

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  perform-build:
    uses: jpbarto/cicd-environ.cicd/.github/workflows/reuse-build.yaml@main
    with:
      deliver_snapshot: false
